### ISSUE TITLE
Usage of  `Data/Simulations/DOI.X/` can lead to problems

### ISSUE THREAD

**Issue by hseara** [NMRLipids/NMRlipidsVIpolarizableFFs#3]
In AddData.ipynb script, we now use  `Data/Simulations/DOI.X/` instead of  `Data/Simulations/CHEKSUM/`. Although I understand your reasoning, this is something I discarded when I did the original script for several reasons: 

1.  Not all databases provide DOI. Therefore, we are restricting the target DataBases to Zenodo.org, which, to my knowledge, is the only repository supplying DOIs. 

2.  There can be several simulations inside a DOI. I know that you have the X in DOI.X to take care of this. The problem is that choosing X  is now a decision for the user. If there are two simulations in one DOI, which is simulation one and which is two? This open user decision also can potentially lead to duplicated entries or strange directory names where several people upload the same publicly available trajectory from the same DOI but different X.

3. This decision will be hard to change once the DB  folder is uploaded.

4. Using capital letters in the folder's name can lead to a problems when using OS which are not case sensitive such as windows.

**Comment by batukav** [comment]
Hi,

Thank you very much for these comments.


> Using capital letters in the folder's name can lead to a problems when using OS which are not case sensitive such as windows.

Good point. I issued a fix for this.

Regarding points 1) and 2), would you suggest us to use Checksums instead of DOI's?

**Comment by hseara** [comment]
> Regarding points 1) and 2), would you suggest us to use Checksums instead of DOI's?

Yes, I will use checksums instead.

Also, I forgot. There is a functional limit in the number of directories one directory can hold. The number is not as big as many tend to think.  A solution to the problem will be to create a nested directory structure:
```
simulations/aaa/
simulations/aaa/aaaxlksjlkjskljs/
simulations/aaa/aaalssalokdsjls/
simulations/ada/
simulations/ada/adakjhasjkhkjh/
simulations/ada/adalskjlskjslkjs/
simulations/ada/adawaspolewq/
simulations/edf/edf/
simulations/edf/edfslkjdalkjdalk/
simulations/edf/edfklasiaujloija/
...
```
Where the weird strings are the checksums. This is used for example in projects such as spack.

**Comment by markussmiettinen** [comment]
> Also, I forgot. There is a functional limit in the number of directories one directory can hold. The number is not as big as many tend to think. A solution to the problem will be to create a nested directory structure:
> 
> ```
> simulations/aaa/
> simulations/aaa/aaaxlksjlkjskljs/
> simulations/aaa/aaalssalokdsjls/
> simulations/ada/
> simulations/ada/adakjhasjkhkjh/
> simulations/ada/adalskjlskjslkjs/
> simulations/ada/adawaspolewq/
> simulations/edf/edf/
> simulations/edf/edfslkjdalkjdalk/
> simulations/edf/edfklasiaujloija/
> ...
> ```

Why not

> ```
> simulations/aaa/xlk/sjl/kjs/ljs/
> simulations/aaa/lss/alo/kds/jls/
> simulations/ada/kjh/asj/khk/jjh/
> simulations/ada/lsk/jls/kjs/lkj/
> simulations/ada/was/pol/ewq/pro/
> simulations/edf/slk/jda/lkj/dal/
> simulations/edf/kla/sia/ujl/oij/
> ...
> ```

this would avoid the problem that when there starts to be billions of data, also the first set of directories will start to overfill. The latter approach should work as long as the checksums are unique, right?

**Comment by hseara** [comment]
@markussmiettinen The method that uses three letters is known to works for nearly any reasonable number of records. It divides the number of subfolders/files inside a given directory by a factor of 4096 (16**3). For the NMRlipids project, perhaps using two-letter only of the checksum should be enough, i.e., 256. My two cents.

**Comment by batukav** [comment]
What about

> simulations/4char/4morechar/traj

kind of structure, where the _4char_ and _4morechar_ are generated by the first and second 4 characters of the checksums of the associated topology file and the _traj_ directory is generated by the checksum of the trajectory file? We can also simply change the number of characters we are using. This could be easier to implement, in my case.

**Comment by hseara** [comment]
@batukav 4chars provide 65536 folders in the first level which is quite a lot. With this depth level, some operations like listing files and search operations will be already slow but manageable.
```
https://stackoverflow.com/questions/466521/how-many-files-can-i-put-in-a-directory
```
I would still prefer 3 chars as directory names for the first level, i.e., 4096 dir in the 1st level.  With 1 million trajectories, which is a lot for the kind of project we are talking about, it will result in ~244 directories on average in the second level. Therefore, we have a lot of room, in case the project becomes a hot hit.

Finally, I would use full checksums, both in the second level for the topology and for the trajectory file in the third level. This third level might be interesting in case of multiple replicas generated from the same top file. Nice solution. 

```
simulations/3char/checksum_top/checksum_trj/
```

I admit that the resulting path will be long, but who cares as is the machine who needs to access it. I do not anybody to type the paths. 

This is my opinion. But feel free to do whatever you consider best.

**Comment by markussmiettinen** [comment]
> @markussmiettinen The method that uses three letters is known to works for nearly any reasonable number of records.

Sure. But if one breaks the checksum in nested 3-letter directories, one can drop the words 'nearly' and 'reasonable'.

**Comment by batukav** [comment]
@hseara @markussmiettinen 

I have updated the AddData.ipynb such that the directory naming follows '/asd/fgh/topology_checksum/trajectory_checksum'

where 'asd' and 'fgh' are the 1-3rd and 4-6th letters of the topology checksum. With these changes, I think we are creating enough room for upcoming uploads.

If you all agree with these changes, I'll close the issue.

**Comment by ohsOllila** [comment]
I was testing this version in NMRlipidsIVb and the resulting data is here: https://github.com/NMRLipids/NMRlipidsIVPEandPG/tree/master/Data/Simulations

I added the DOI and a system description into the dictionary because this folder structure does not connect the hash to a dataset in Zenodo or system information. 

I also made the first script that is reading the data from this format: https://github.com/NMRLipids/NMRlipidsIVPEandPG/blob/master/scripts/plotDATA.ipynb 
It makes the HG+GLY order parameter plot from the present POPC, POPE, POPG and POPS simulations. The result is here: https://github.com/NMRLipids/NMRlipidsIVPEandPG/blob/master/Figs/CHARMMfromLIPIDS-eps-converted-to.pdf

From the databank point of view, we need to decide which information will be saved in the dictionary, and how this will be retrieved (what will the contributor give and what will be read from the data).
Currently, this is a free text format in dictionary variable @SYSTEM, which is not a sustainable solution. We need unique notations that the data can be accessed with the analysis scripts.  
I was hoping to discuss this in the NMRlipids workshop.

I also added the notebook in raw python format in the Git (https://github.com/NMRLipids/NMRlipidsVIpolarizableFFs/blob/master/DataContribtionScripts/AddData.py) because Git version control does not work very well for jupyter-notebook. The changes I have made more easily readable from here: https://github.com/NMRLipids/NMRlipidsVIpolarizableFFs/commit/21222f07668f0334415131b227bebbeabdbaf458
(Althought there are still useless marks for the changes in the cell numbers because I moved working directory definition into the first cell, but these will disappear in the next update). There are also other options to make version control work for jupyter-notebooks, but for now we could go with this option, i.e., keeping also the raw python version in the Git.
